theme: jekyll-theme-cayman
title: Welcome to the PharmTab Data Repository

collections: 
- datasets
collections_dir: datasets
collections:
  datasets:
    output: true
    permalink: /_datasets/:path/
