theme: jekyll-theme-cayman
title: Welcome to the Pharmtab Raw Data Repository

collections: 
- datasets
collections_dir: datasets
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
